# Generated by Django 5.2.4 on 2025-10-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
    ]
