# Generated by Django 5.2.4 on 2025-10-07 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employee_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_manager', models.ForeignKey(limit_choices_to={'role': 'head_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'manager'}, related_name='assigned_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.team')),
            ],
        ),
    ]
